steps:
  # Install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "backend/requirements.txt", "--user"]

  # Run unit tests
  #- name: python
  #  entrypoint: python
  #  args: ["-m", "pytest", "backend/API/tests/"] 

  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'us-central1-docker.pkg.dev/$PROJECT_ID/purdue-eats/fimage:$SHORT_SHA', '.']

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'us-central1-docker.pkg.dev/$PROJECT_ID/purdue-eats/fimage:$SHORT_SHA']

  # Deploy to Cloud Run
  - name: google/cloud-sdk
    args: ['gcloud', 'run', 'deploy', 'app', 
           '--image=us-central1-docker.pkg.dev/$PROJECT_ID/purdue-eats/fimage:$SHORT_SHA', 
           '--region', 'us-central1', '--platform', 'managed', 
           '--allow-unauthenticated']

# Store images in Google Artifact Registry
images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/purdue-eats/fimage:$SHORT_SHA
